name: Analyze And Test
'on': pull_request
jobs:
  analyze_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd werewolves
          sudo snap install flutter --classic
          flutter doctor
          flutter analyze
          flutter test
